### ISSUE TITLE
Unable to parse empty if statements

### ISSUE THREAD

**Issue by Gorea235** [KvanTTT/CSharp-Minifier#44]
If you have a statement like the following

```csharp
if (a == b)
{ }
```

or

```csharp
if (a == b) ;
```

The minifier seems to crash. The problem seems to be that GetLeafNodeString in Minifier.cs is assuming that the block contains something, but it is counted as empty (the node is set to ';' regarless or whether you used braces or a semicolon). The exception is below

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=CSharpMinifier
  StackTrace:
   at CSharpMinifier.Minifier.GetLeafNodeString(AstNode node) in C:\Users\luke\Documents\Development\External\CSharp-Minifier\CSharpMinifier\Minifier.cs:line 868
   at CSharpMinifier.Minifier.RemoveSpacesAndAppend(AstNode node, StringBuilder line, StringBuilder result) in C:\Users\luke\Documents\Development\External\CSharp-Minifier\CSharpMinifier\Minifier.cs:line 694
   at CSharpMinifier.Minifier.RemoveSpacesAndAppend(AstNode node, StringBuilder line, StringBuilder result) in C:\Users\luke\Documents\Development\External\CSharp-Minifier\CSharpMinifier\Minifier.cs:line 750
   at CSharpMinifier.Minifier.RemoveSpacesAndAppend(AstNode node, StringBuilder line, StringBuilder result) in C:\Users\luke\Documents\Development\External\CSharp-Minifier\CSharpMinifier\Minifier.cs:line 750
   at CSharpMinifier.Minifier.RemoveSpacesAndAppend(AstNode node, StringBuilder line, StringBuilder result) in C:\Users\luke\Documents\Development\External\CSharp-Minifier\CSharpMinifier\Minifier.cs:line 750
   at CSharpMinifier.Minifier.RemoveSpacesAndAppend(AstNode node, StringBuilder line, StringBuilder result) in C:\Users\luke\Documents\Development\External\CSharp-Minifier\CSharpMinifier\Minifier.cs:line 750
   at CSharpMinifier.Minifier.GetStringWithoutSpaces(IEnumerable`1 nodes) in C:\Users\luke\Documents\Development\External\CSharp-Minifier\CSharpMinifier\Minifier.cs:line 679
   at CSharpMinifier.Minifier.GetStringWithoutSpaces() in C:\Users\luke\Documents\Development\External\CSharp-Minifier\CSharpMinifier\Minifier.cs:line 660
   at CSharpMinifier.Minifier.Minify() in C:\Users\luke\Documents\Development\External\CSharp-Minifier\CSharpMinifier\Minifier.cs:line 148
   at CSharpMinifier.Minifier.MinifyFromString(String csharpCode) in C:\Users\luke\Documents\Development\External\CSharp-Minifier\CSharpMinifier\Minifier.cs:line 127
   at CSharpMinifier.GUI.frmMain.btnMinify_Click(Object sender, EventArgs e) in C:\Users\luke\Documents\Development\External\CSharp-Minifier\CSharpMinifier.GUI\frmMain.cs:line 126
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at CSharpMinifier.GUI.Program.Main() in C:\Users\luke\Documents\Development\External\CSharp-Minifier\CSharpMinifier.GUI\Program.cs:line 16
```

**Comment by KvanTTT** [comment]
I have not an exception but have an incorrect output. Could you please add the full source of the sample?

**Comment by KvanTTT** [comment]
I also added `Unsafe` option that would remove the following fragments completely:

```csharp
if (a == b)
{ }
```

Such removing can have side effects in comparison. That's why it's unsafe.
